### ISSUE TITLE
set up cypress testing

### ISSUE THREAD

**Issue by yochannah** [intermine/wizard#10]
set up cypress https://www.cypress.io/ ui test to check
- registration 
- login
- check logout works
- check the alert boxes behave as expected. 

(we can add other tasks later on, but not much else is supported yet). 

use the docker-compose command from the readme to generate the environment correctly. 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by yochannah** [comment]
- check logout works
- check the alert boxes behave as expected.

**Comment by ankitskvmdam** [comment]
I would like to work on this.

**Comment by yochannah** [comment]
awesome, go ahead! :grin:
