### ISSUE TITLE
[easy task if you know eslint + node] Don't lint the public/dist directory

### ISSUE THREAD

**Issue by yochannah** [intermine/wizard#15]
the public/dist directory contains built files and should not be linted. We should update our eslint config to ignore this directory. 

## if you want to pick up this task

1. Comment on this issue stating that you intend to work on the task
2. When you're ready, add your work to the repo and create a pull request.

### What to do if you need help

Mention @yochannah, tweet [@yoyehudi](http://www.twitter.com/yoyehudi), pop by to say hi on [chat](http://chat.intermine.org) or if needed email yo@intermine.org <3

**Comment by varshannagarajan** [comment]
Hey, I would like to work on this issue if possible. If it's OK with you with I will create the pull request after Oct 1st so that it's part of Hacktoberfest.

**Comment by yochannah** [comment]
Sounds perfect! :) we'll look forward to the PR next week!

**Comment by varshannagarajan** [comment]
Looks like the issue has been fixed.

**Comment by yochannah** [comment]
Fixed by @ikhemissi  in #18
