### ISSUE TITLE
'My profile' in navbar - should indicate if logged in

### ISSUE THREAD

**Issue by yochannah** [intermine/wizard#21]
Currently the navbar says "my profile" whether or not you're logged in. We should show a person's first name or email in the top right if they're logged in, instead. 

![image](https://user-images.githubusercontent.com/9271438/68127257-6a9f6700-ff0d-11e9-9232-92e539512641.png)

**Comment by ankitskvmdam** [comment]
I would like to work on this..

**Comment by yochannah** [comment]
Thank you!!

**Comment by pooja2299** [comment]
Hi @yochannah I am an outreachy aspirant. I think this issue has been solved. Since u have not closed it can i still work on it?
